global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'mohawk'
    static_configs:
      - targets: ['control:8080', 'datapath:8080']
  - job_name: 'fl'
    static_configs:
      - targets: ['fl-coordinator:9001']
  - job_name: 'swip'
    static_configs:
      - targets: ['swip-client:9101']
