apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mohawk-allow-same-namespace
  namespace: mohawk
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}
  egress:
    - to:
        - podSelector: {}
